// import './globals.css'
import FooterScreen from '@/components/layouts/footer.layout'
import HeaderScreen from '@/components/layouts/header.layout'
import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from 'next'
import { Space_Grotesk } from "@next/font/google"

const spaceGrotesk = Space_Grotesk({
  subsets: ['vietnamese'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <HeaderScreen/>
        {children}
        {/* <FooterScreen/> */}
      </body>
      
    </html>
  )
}
